"""
app.py — Python backend for Toddler Music Box (FastAPI)

  GET /              → the PWA frontend (static/index.html)
  GET /api/songs     → list of nursery songs (could later return melodies generated by a VAE)
  GET /api/health    → health check
  GET /sw.js         → Service Worker (must be served from the root to control the whole site)

Run locally: uvicorn app:app --reload --port 8000
then open http://localhost:8000
"""
import json
from pathlib import Path

from fastapi import FastAPI
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles

STATIC = Path(__file__).parent / "static"

app = FastAPI(title="Toddler Music Box API", version="1.0.14")


@app.get("/api/health")
def health():
    return {"status": "ok"}


@app.get("/api/songs")
def songs():
    # Week 1 extension: this could later return new melodies generated by a VAE
    return json.loads((STATIC / "songs.json").read_text(encoding="utf-8"))


@app.get("/sw.js", include_in_schema=False)
def service_worker():
    return FileResponse(
        STATIC / "sw.js",
        media_type="application/javascript",
        headers={"Cache-Control": "no-cache", "Service-Worker-Allowed": "/"},
    )


@app.get("/manifest.webmanifest", include_in_schema=False)
def manifest():
    return FileResponse(STATIC / "manifest.webmanifest",
                        media_type="application/manifest+json")


# Other static files (index.html, app.js, sounds/…) — mounted last so /api is not shadowed
app.mount("/", StaticFiles(directory=STATIC, html=True), name="static")
