// build.mjs - static/app.bundle.js for every browser, from old iPads (Safari 9, iOS 9) to the newest.
//   legacy-shim.js  +  whatwg-fetch  +  piano.js + app.js (Babel -> ES5, core-js polyfills only where used)
// Run:  cd compat && npm install && npm run build   (then python compat_css.py for the CSS)
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { transformSync } from "@babel/core";
import { build } from "esbuild";

const STATIC = new URL("../static/", import.meta.url);
const TMP = new URL("./.build/", import.meta.url);
mkdirSync(TMP, { recursive: true });
const TARGETS = "iOS >= 9, Safari >= 9, Chrome >= 49, Firefox >= 52, Edge >= 18, > 0.2%, not dead";

const babel = (file) => transformSync(readFileSync(new URL(file, STATIC), "utf8"), {
  filename: file, sourceType: "script", babelrc: false, configFile: false, comments: false,
  presets: [["@babel/preset-env", { targets: TARGETS, useBuiltIns: "usage", corejs: "3.50", modules: false, forceAllTransforms: true }]],
}).code;

writeFileSync(new URL("piano.es5.js", TMP), babel("piano.js"));
writeFileSync(new URL("app.es5.js", TMP), babel("app.js"));
writeFileSync(new URL("entry.js", TMP), [
  'require("../legacy-shim.js");',
  'require("whatwg-fetch");',
  'require("./piano.es5.js");',
  'require("./app.es5.js");',
].join("\n"));

await build({
  entryPoints: [new URL("entry.js", TMP).pathname], bundle: true, format: "iife", target: "es5",
  minify: true, legalComments: "none", outfile: new URL("app.bundle.js", STATIC).pathname,
  banner: { js: "/* GENERATED by compat/build.mjs from piano.js + app.js (+ polyfills) - do not edit */" },
  logLevel: "warning",
});
console.log("static/app.bundle.js written");
