/* Toddler Music Box — frontend (HTML/JS + Web Audio API)
  * 1. No start screen: the main screen shows at once; the first tap anywhere unlocks sound and goes fullscreen
  * 2. Pre-loads and decodes 25 WAV files generated by Python → instant, low-latency sound
  * 3. Play-along mode: melodies come from the Python backend (/api/songs); the next key is highlighted
  * 4. Registers a Service Worker → works offline and can be "Added to Home Screen"
  * 5. 12 languages (source of truth: i18n.py in Python → static/i18n.json)
  * 6. "Current note" layer: staff notation (rendered by Python + verovio) and the key to press
  * 8. Quiz: all 8 notes of the selected clef, each once, in random order, answered on a real piano (microphone) or the on-screen keys
  * 7. Clef menu: treble clef (middle C to C5) / bass clef (C3 to middle C);
  *    keys, sounds, staff images and piano listening all shift by one octave
  * 9. Play-mode menu: on-screen keys (default) or a real piano — the microphone is only used for the real piano
 */
(() => {
  "use strict";

  // White-key "slots": pc = pitch class, up = one octave higher (the rightmost C)
  const WHITE_SLOTS = [
    { pc: "C", idx: 0, shape: "circle" },
    { pc: "D", idx: 1, shape: "square" },
    { pc: "E", idx: 2, shape: "triangle" },
    { pc: "F", idx: 3, shape: "star" },
    { pc: "G", idx: 4, shape: "hexagon" },
    { pc: "A", idx: 5, shape: "diamond" },
    { pc: "B", idx: 6, shape: "heart" },
    { pc: "C", idx: 0, shape: "arrow", up: 1, high: true },   // octave above: same color, up arrow
  ];
  // Black keys: between = which two white keys it sits between (positioned by JS)
  const BLACK_SLOTS = [
    { pc: "Cs", idx: 0, between: [0, 1] },
    { pc: "Ds", idx: 1, between: [1, 2] },
    { pc: "Fs", idx: 3, between: [3, 4] },
    { pc: "Gs", idx: 4, between: [4, 5] },
    { pc: "As", idx: 5, between: [5, 6] },
  ];
  const PC = ["C", "Cs", "D", "Ds", "E", "F", "Fs", "G", "Gs", "A", "As", "B"];
  const noteNum = (id) => PC.indexOf(id.slice(0, -1)) + 12 * (+id.slice(-1) + 1);

  // Clef: G = treble clef (C4–C5), F = bass clef (C3–C4)
  let clef = "G";
  try { if (localStorage.getItem("clef") === "F") clef = "F"; } catch (_) {}
  const baseOct = () => (clef === "G" ? 4 : 3);
  // Colors: everything pink in treble clef, everything light blue in bass clef (same families as generate_assets.py)
  // Healing comic style: soft pastel fill + a deeper outline of the same color (outline ≥ 4.4:1 on white)
  // "Sakura Sky" palette (chosen by the parent): cherry-blossom pink for treble, clear-sky blue for bass
  const CLEF_COLOR = { G: "#FBC8D8", F: "#C3E5F8" };   // pastel fill
  const CLEF_LINE  = { G: "#C04877", F: "#2A78A8" };   // deeper outline (4.7:1 / 4.8:1 on white)
  // Middle C (C4) is always pink, so the rightmost C in bass clef reminds kids "this is middle C"
  const colorOf = (note) => (note === "C4" ? CLEF_COLOR.G : CLEF_COLOR[clef]);
  const lineOf  = (note) => (note === "C4" ? CLEF_LINE.G : CLEF_LINE[clef]);
  const noteOf = (slot) => slot.pc + (baseOct() + (slot.up || 0));
  // Middle C (C4) is always a circle; one octave up = up arrow, one octave down = down arrow
  function shapeOf(slot) {
    if (slot.pc !== "C") return slot.shape;
    const oct = +noteOf(slot).slice(-1);
    return oct === 4 ? "circle" : oct > 4 ? "arrow" : "arrowDown";
  }
  // Every note across both octaves (treble and bass share middle C)
  const ALL_NOTES = [...new Set([...PC.map((p) => p + 3), ...PC.map((p) => p + 4), "C5"])];

  // Every shape is an SVG drawn in the same 100×100 box, filled edge to edge and outlined with the same
  // rounded stroke, so all shapes look equally big and equally bold (no letters, numbers or staff on the keys)
  const SHAPES_SVG = {
    circle: "M50 5 A45 45 0 1 1 49.99 5 Z",
    square: "M20 8 L80 8 Q92 8 92 20 L92 80 Q92 92 80 92 L20 92 Q8 92 8 80 L8 20 Q8 8 20 8 Z",
    triangle: "M50 6 L96 92 L4 92 Z",
    star: "M50.0 4.0 L64.7 33.8 L97.6 38.5 L73.8 61.7 L79.4 94.5 L50.0 79.0 L20.6 94.5 L26.2 61.7 L2.4 38.5 L35.3 33.8 Z",
    hexagon: "M27 9 L73 9 L96 50 L73 91 L27 91 L4 50 Z",
    diamond: "M50 2 L98 50 L50 98 L2 50 Z",
    heart: "M50 88 C22 68 6 52 6 33 C6 18 17 8 30 8 C39 8 46 13 50 21 C54 13 61 8 70 8 C83 8 94 18 94 33 C94 52 78 68 50 88 Z",
    arrow: "M50 4 L96 52 L70 52 L70 96 L30 96 L30 52 L4 52 Z",        // up arrow: one octave higher
    arrowDown: "M50 96 L96 48 L70 48 L70 4 L30 4 L30 48 L4 48 Z",     // down arrow: one octave lower
  };

  const MAX_VOLUME = 0.7;          // protects little ears: volume cap
  const keysEl = document.getElementById("keys");
  const songSel = document.getElementById("song");
  const modeSel = document.getElementById("mode");      // "screen" = on-screen keys (default) | "piano" = real piano (mic)
  const pianoStatus = document.getElementById("pianoStatus");
  const statusEl = document.getElementById("status");

  let ctx = null, master = null;
  const buffers = {};              // note -> AudioBuffer
  const keyEls = {};               // note -> <button> (rebuilt when the clef changes)
  let whiteEls = [];               // white keys in slot order
  let song = null, songPos = 0, curNotes = [];     // curNotes: the melody moved to the current clef's octave

  /* ---------------- Languages ---------------- */
  let I18N = null, lang = "en", T = {};
  const langSel = document.getElementById("lang");

  // Note names: white keys use the language's solfège; black keys = white key below + ♯
  function noteName(note) {
    const k = keyEls[note]._info;
    return T.notes[k.idx] + (note.includes("s") ? "♯" : "");
  }

  function pickLang(list) {
    let saved = null;
    try { saved = localStorage.getItem("lang"); } catch (_) {}
    if (saved && list.includes(saved)) return saved;
    for (const l of navigator.languages || [navigator.language || "en"]) {
      const low = l.toLowerCase();
      if (/^zh-(tw|hk|mo|hant)/.test(low)) return "zh-Hant";
      if (low.startsWith("zh")) return "zh-Hans";
      const base = low.split("-")[0];
      if (list.includes(base)) return base;
    }
    return "en";
  }

  function applyLang() {
    T = I18N.strings[lang];
    document.documentElement.lang = lang;
    document.title = T.appName === "Toddler Music Box" ? T.appName : `${T.appName} · Toddler Music Box`;
    for (const el of Object.values(keyEls)) {
      const k = el._info, name = noteName(el.dataset.note);
      el.setAttribute("aria-label", el.dataset.shape === "arrow" ? `${T.high} ${name}` : el.classList.contains("black") ? `${name} · ${T.black}` : name);
    }
    for (const o of songSel.options) o.textContent = o._song ? T[o._song.title] || o._song.title : T.free;
    songSel.setAttribute("aria-label", T.song);
    clefSel.options[0].textContent = T.treble;
    clefSel.options[1].textContent = T.bass;
    clefSel.setAttribute("aria-label", T.clef);
    micTitle.textContent = T.micTitle;
    micClose.textContent = T.close;
    setMicDialog();
    modeSel.options[0].textContent = T.modeScreen;
    modeSel.options[1].textContent = T.modePiano;
    modeSel.setAttribute("aria-label", T.mode);
    quizBtn.textContent = quiz ? `■ ${T.quizEnd}` : T.quiz;
    menuBtn.setAttribute("aria-label", T.menu);
    menuBtn.title = T.menu;
    setPlayBtn();
    setExitBtn();
    if (pianoState) pianoStatus.textContent = T[pianoState] || "";
    nowEl.setAttribute("aria-label", T.now);          // no visible label; screen readers still hear "Current note"
    langSel.setAttribute("aria-label", T.language);
    // The closed language menu always shows the word "Language" in the current language
    // (not the language name); in the open list the current language has a check mark.
    langSel.options[0].textContent = T.language;
    for (const o of langSel.options) if (o.value) o.textContent = (o.value === lang ? "\u2713 " : "") + o._label;
    langSel.value = "";
    if (nowNote) showNow(nowNote, !!quiz);
  }

  async function loadI18n() {
    const r = await fetch("i18n.json");
    I18N = await r.json();
    const codes = I18N.langs.map(([c]) => c);
    const title = new Option("", "");                   // shows "Language" (translated) when the menu is closed
    title.hidden = true;
    title.disabled = true;
    langSel.add(title);
    for (const [code, label] of I18N.langs) { const o = new Option(label, code); o._label = label; langSel.add(o); }
    lang = pickLang(codes);
    applyLang();
  }
  langSel.addEventListener("change", () => {
    if (!langSel.value) return;
    lang = langSel.value;
    try { localStorage.setItem("lang", lang); } catch (_) {}
    applyLang();
  });

  /* ---------------- "Current note" layer: staff + key to press ---------------- */
  const nowEl = document.getElementById("now");
  const nowStaff = document.getElementById("nowStaff");
  const nowKey = document.getElementById("nowKey");
  let nowNote = null;

  // After a right note the card keeps showing that answer for a moment (HOLD_MS) before the next target appears.
  const HOLD_MS = 750;
  let holdUntil = 0, holdT = 0;
  function showNow(note, hideAnswer = false, fromHold = false) {
    if (!fromHold) clearTimeout(holdT);            // any direct update cancels a waiting one
    nowNote = note;
    const key = keyEls[note];
    nowEl.classList.remove("empty");
    const src = `staff/${clef}/${note}.svg`;
    if (nowStaff.getAttribute("src") !== src) {
      nowStaff.src = src;
      nowEl.classList.remove("pop"); void nowEl.offsetWidth; nowEl.classList.add("pop");
    }
    nowStaff.alt = noteName(note);
    // Mini key: copies the key's color and shape
    nowKey.className = "mini-key" + (key.classList.contains("black") ? " black" : "");
    nowKey.dataset.shape = key.dataset.shape || "";
    nowKey.style.setProperty("--c", key.style.getPropertyValue("--c"));
    nowKey.style.setProperty("--cl", key.style.getPropertyValue("--cl"));
    nowKey.innerHTML = key.classList.contains("black") ? "" : key.querySelector(".shape").outerHTML;
    if (hideAnswer) {                               // quiz: hide the answer (which key to press)
      nowKey.className = "mini-key ask";
      nowKey.innerHTML = `<span class="ask-mark">?</span>`;
    }
    applyCue();
  }

  // The note to press: its shape on the card and the same shape on the right key bounce and blink
  // together, in step (both animations are restarted at the same moment). In the quiz only the "?" moves,
  // so the answer is not given away. Nothing moves during the Listen demo or in free play.
  function currentTarget() {
    if (demo) return null;
    if (quiz) return quiz.notes[quiz.pos];
    if (song) return curNotes[songPos];
    return null;
  }
  function applyCue() {
    document.querySelectorAll(".cue").forEach((e) => e.classList.remove("cue"));
    const target = currentTarget();
    if (!target) return;
    const els = [];
    if (nowNote === target) els.push(nowKey.querySelector(".shape, .ask-mark"));
    if (!quiz && keyEls[target]) els.push(keyEls[target].querySelector(".shape"));
    const live = els.filter(Boolean);
    void document.body.offsetWidth;                  // restart both animations at the same time
    live.forEach((e) => e.classList.add("cue"));
  }

  // Show the next target — but if the child just played a right note, wait until its answer has been seen
  function showTarget(note, hideAnswer = false) {
    const wait = holdUntil - performance.now();
    if (wait > 0) {
      clearTimeout(holdT);
      holdT = setTimeout(() => showNow(note, hideAnswer, true), wait);
    } else showNow(note, hideAnswer);
  }

  // Right note (songs and quiz): the card shows the answer (staff + shape) with a happy pulse.
  function rightNote(note) {
    showNow(note);
    nowEl.classList.remove("right"); void nowEl.offsetWidth; nowEl.classList.add("right");
    holdUntil = performance.now() + HOLD_MS;
    reward(note);
  }

  /* ---------------- Right-note reward (chosen by the parent: #1, #2, #4, #5, #10, at random) ---------------- */
  // Above the key that was played: only the note on the staff (transparent background), with one of
  // five little effects around it: confetti, twinkling stars, hearts, ripple rings or orbiting music notes.
  // Colors: Sakura Sky pink + blue, beige, black, white only. It never blocks the keys (pointer-events: none).
  const RW_COLORS = ["#FBC8D8", "#C04877", "#C3E5F8", "#2A78A8", "#EADBC8", "#FFFFFF"];
  const RW_STAR = '<svg viewBox="-50 -50 100 100"><path d="M0-46C6-10 10-6 46 0 10 6 6 10 0 46-6 10-10 6-46 0-10-6-6-10 0-46Z"/></svg>';
  const RW_HEART = '<svg viewBox="-6 -6 112 112"><path d="M50 88 C22 68 6 52 6 33 C6 18 17 8 30 8 C39 8 46 13 50 21 C54 13 61 8 70 8 C83 8 94 18 94 33 C94 52 78 68 50 88 Z"/></svg>';
  const RW_NOTE = '<svg viewBox="0 0 40 40"><path d="M15 30V8l18-4v20" fill="none" stroke="#111" stroke-width="3"/><ellipse cx="10.5" cy="30.5" rx="6" ry="4.6"/><ellipse cx="28.5" cy="25.5" rx="6" ry="4.6"/></svg>';
  const rw = (i, s) => { const x = Math.sin(i * 999 + s * 77 + Math.random()) * 10000; return x - Math.floor(x); };
  const RW_BUILD = {
    confetti(L, add) { for (let i = 0; i < 22; i++) { const a = rw(i, 1) * Math.PI * 2, r = 18 + rw(i, 2) * 26;
      add("", { "--dx": Math.cos(a) * r + "cqw", "--dy": Math.sin(a) * r * .8 - 10 + "cqw", "--r": (rw(i, 3) * 720 - 360) + "deg", "--d": rw(i, 4) * .12 + "s", "--c": RW_COLORS[i % 5] }); } },
    sparkle(L, add) { for (let i = 0; i < 10; i++) { const a = i / 10 * Math.PI * 2, r = 36 + rw(i, 2) * 8;
      add(RW_STAR, { "--dx": Math.cos(a) * r + "cqw", "--dy": Math.sin(a) * r * .75 + "cqw", "--d": (i % 5) * .08 + "s", "--c": RW_COLORS[[0, 2, 4, 1, 3][i % 5]] }); } },
    hearts(L, add) { for (let i = 0; i < 12; i++) { const a = -Math.PI / 2 + (rw(i, 1) - .5) * 2.6, r = 30 + rw(i, 2) * 16;
      add(RW_HEART, { "--dx": Math.cos(a) * r + "cqw", "--dy": Math.sin(a) * r + "cqw", "--r": (rw(i, 3) * 60 - 30) + "deg", "--s": (7 + rw(i, 4) * 6) + "cqw", "--d": rw(i, 5) * .3 + "s", "--c": RW_COLORS[[0, 2, 1, 0, 2, 3][i % 6]] }); } },
    ripple(L, add) { [0, .3, .6].forEach((d, i) => add("", { "--d": d + "s", "--c": RW_COLORS[[0, 2, 1][i]] })); },
    orbit(L, add) { for (let i = 0; i < 6; i++) add(RW_NOTE, { "--a": (i * 60) + "deg", "--d": (i * .04) + "s", "--c": RW_COLORS[[0, 2, 1, 3, 0, 2][i]] }); },
  };
  const RW_KINDS = Object.keys(RW_BUILD);
  let lastKind = "";
  function reward(note) {
    const key = keyEls[note];
    if (!key) return;
    let kind = RW_KINDS[Math.floor(Math.random() * RW_KINDS.length)];
    if (kind === lastKind) kind = RW_KINDS[(RW_KINDS.indexOf(kind) + 1) % RW_KINDS.length];   // never twice in a row
    lastKind = kind;
    const box = document.createElement("div");
    box.className = "reward rw-" + kind;
    box.setAttribute("aria-hidden", "true");
    // only the note on a see-through staff + the see-through effect (no shape, no white background)
    box.innerHTML = `<div class="rw-layer"></div><div class="rw-answer"><img src="staff/${clef}/${note}.svg" alt="" draggable="false"></div>`;
    // The staff note is 1.5 x the key's shape, floats on top of that shape, and stays below the black keys.
    // Layout coordinates (offsetLeft/Top, not screen coordinates), so it also works on rotated phones.
    const shapeEl = key.querySelector(".shape");
    const black = keysEl.querySelector(".key.black");
    const keyBottom = key.offsetTop + key.offsetHeight;
    let img, cx, cy;
    if (shapeEl && !key.classList.contains("black")) {
      const blackBottom = black ? black.offsetTop + black.offsetHeight : key.offsetTop;
      const room = keyBottom - blackBottom;                        // white part of the key below the black keys
      img = Math.min(shapeEl.offsetWidth * 1.5, room * 0.86);
      cx = key.offsetLeft + shapeEl.offsetLeft + shapeEl.offsetWidth / 2;
      cy = key.offsetTop + shapeEl.offsetTop + shapeEl.offsetHeight / 2;
      cy = Math.min(Math.max(cy, blackBottom + img * 0.56), keyBottom - img * 0.52);
    } else {                                                        // (a black key: just above it)
      img = key.offsetWidth * 1.5;
      cx = key.offsetLeft + key.offsetWidth / 2;
      cy = key.offsetTop + key.offsetHeight * 0.5;
    }
    const w = img / 0.62;                                           // .rw-answer is 62 % of the box
    box.style.width = w + "px";
    box.style.left = cx + "px";
    box.style.top = cy + "px";
    const L = box.querySelector(".rw-layer");
    RW_BUILD[kind](L, (html, vars) => {
      const d = document.createElement("div");
      d.className = "rw-p";
      for (const k in vars) d.style.setProperty(k, vars[k]);
      d.innerHTML = html;
      L.appendChild(d);
    });
    keysEl.appendChild(box);
    setTimeout(() => box.remove(), 2100);
  }

  /* ---------------- Quiz finished: a burst of see-through bubbles that the child can pop ---------------- */
  let party = null;
  function bubbleParty() {
    endBubbleParty();
    const app = document.getElementById("app");
    party = document.createElement("div");
    party.className = "bubble-party";
    party.setAttribute("aria-hidden", "true");
    const COLS = 7, ROWS = 4;                                 // a loose grid, so the bubbles fill the whole screen
    for (let i = 0; i < COLS * ROWS; i++) {
      const b = document.createElement("div");
      b.className = "pb";
      const s = 11 + Math.random() * 10;                      // size, % of the app height
      const x = ((i % COLS) + 0.2 + Math.random() * 0.6) / COLS * 100;
      const y = (Math.floor(i / COLS) + 0.2 + Math.random() * 0.6) / ROWS * 100;
      b.style.setProperty("--s", s + "cqh");
      b.style.setProperty("--x", Math.min(94, Math.max(6, x)) + "cqw");
      b.style.setProperty("--y", Math.min(90, Math.max(10, y)) + "cqh");
      b.style.setProperty("--d", (Math.random() * 0.25) + "s");
      b.style.setProperty("--f", (5 + Math.random() * 4) + "s");
      b.style.setProperty("--tint", ["#FBC8D8", "#C3E5F8", "#EADBC8"][i % 3]);
      b.addEventListener("pointerdown", (e) => { e.stopPropagation(); popBubble(b); });
      party.appendChild(b);
    }
    app.appendChild(party);
    party._t = setTimeout(endBubbleParty, 3000);              // they disappear by themselves after 3 s
  }
  function popBubble(b) {
    if (b.classList.contains("popped")) return;
    b.classList.add("popped");
    popSound();
    setTimeout(() => {
      b.remove();
      if (party && !party.querySelector(".pb:not(.popped)")) endBubbleParty();
    }, 320);
  }
  function endBubbleParty() {
    if (!party) return;
    clearTimeout(party._t);
    const p = party;
    party = null;
    p.classList.add("bye");
    setTimeout(() => p.remove(), 600);
  }
  function popSound() {                                       // a soft little "pop" (low, very short)
    if (!ctx) return;
    if (ctx.state === "suspended") ctx.resume();
    const t = ctx.currentTime, o = ctx.createOscillator(), g = ctx.createGain();
    o.type = "sine";
    o.frequency.setValueAtTime(620, t);
    o.frequency.exponentialRampToValueAtTime(180, t + 0.09);
    g.gain.setValueAtTime(0.0001, t);
    g.gain.exponentialRampToValueAtTime(0.35, t + 0.008);
    g.gain.exponentialRampToValueAtTime(0.0001, t + 0.12);
    o.connect(g).connect(master);
    o.start(t);
    o.stop(t + 0.14);
  }


  /* ---------------- Keys (built for the current clef) ---------------- */
  function buildKeys() {
    keysEl.innerHTML = "";
    for (const n in keyEls) delete keyEls[n];
    whiteEls = WHITE_SLOTS.map((k) => {
      const note = noteOf(k);
      const b = document.createElement("button");
      b.className = "key";
      b.dataset.note = note;
      const shape = shapeOf(k);
      b.dataset.shape = shape;
      b.style.setProperty("--c", colorOf(note));
      b.style.setProperty("--cl", lineOf(note));
      // Only a big, simple shape on each key — easy for toddlers to see
      b.innerHTML = `<span class="shape" aria-hidden="true"><svg viewBox="0 0 100 100"><path d="${SHAPES_SVG[shape]}"/></svg></span>`;
      b._info = k;
      keysEl.appendChild(b);
      keyEls[note] = b;
      return b;
    });
    /* Black-key layer (on top of the white keys, positioned dynamically) */
    for (const k of BLACK_SLOTS) {
      const note = noteOf(k);
      const b = document.createElement("button");
      b.className = "key black";
      b.dataset.note = note;
      b.style.setProperty("--c", CLEF_COLOR[clef]);
      b.style.setProperty("--cl", CLEF_LINE[clef]);
      b._info = k;
      keysEl.appendChild(b);
      keyEls[note] = b;
    }
    layoutBlackKeys();
  }

  // Uses offsetLeft/offsetWidth (layout coordinates) so it stays correct when CSS rotates the screen 90°
  function layoutBlackKeys() {
    for (const k of BLACK_SLOTS) {
      const el = keyEls[noteOf(k)];
      const L = whiteEls[k.between[0]];
      const R = whiteEls[k.between[1]];
      if (!el || !L || !R) continue;
      const w = L.offsetWidth * 0.6;
      el.style.width  = w + "px";
      el.style.height = L.offsetHeight * 0.55 + "px";
      el.style.left   = (L.offsetLeft + L.offsetWidth + R.offsetLeft) / 2 - w / 2 + "px";
      el.style.top    = L.offsetTop + "px";
    }
  }
  // Re-align automatically on resize and when the phone rotates
  new ResizeObserver(layoutBlackKeys).observe(keysEl);
  window.addEventListener("orientationchange", () => setTimeout(layoutBlackKeys, 200));
  buildKeys();

  // pointerdown is ~100 ms faster than click and supports multi-touch
  keysEl.addEventListener("pointerdown", (e) => {
    const key = e.target.closest(".key");
    if (!key) return;
    e.preventDefault();
    press(key, e.clientX, e.clientY);
  });
  const release = (e) => {
    const key = e.target.closest && e.target.closest(".key");
    if (key) key.classList.remove("down");
  };
  keysEl.addEventListener("pointerup", release);
  keysEl.addEventListener("pointercancel", release);
  keysEl.addEventListener("pointerleave", release, true);
  document.addEventListener("contextmenu", (e) => e.preventDefault());

  // Computer keyboard also plays (handy for recording tutorial videos): A S D F G H J K
  // Black keys: W E T Y U (standard layout used by music software)
  const KB = { a: WHITE_SLOTS[0], s: WHITE_SLOTS[1], d: WHITE_SLOTS[2], f: WHITE_SLOTS[3],
               g: WHITE_SLOTS[4], h: WHITE_SLOTS[5], j: WHITE_SLOTS[6], k: WHITE_SLOTS[7],
               w: BLACK_SLOTS[0], e: BLACK_SLOTS[1], t: BLACK_SLOTS[2], y: BLACK_SLOTS[3], u: BLACK_SLOTS[4] };
  const kbNote = (key) => (KB[key.toLowerCase()] ? noteOf(KB[key.toLowerCase()]) : null);
  document.addEventListener("keydown", (e) => {
    if (e.target.tagName === "SELECT" || (e.target.closest && e.target.closest(".cs"))) return;
    const note = kbNote(e.key);
    if (note && !e.repeat) {
      const el = keyEls[note];
      const r = el.getBoundingClientRect();
      press(el, r.left + r.width / 2, r.top + r.height / 2);
    }
  });
  document.addEventListener("keyup", (e) => {
    const note = kbNote(e.key);
    if (note && keyEls[note]) keyEls[note].classList.remove("down");
  });

  // Free play: every key sounds. Songs and quiz: only the right key plays its note and moves on;
  // a wrong key plays a soft kitten "mew" instead (and in the quiz the right key flashes).
  function press(el, x, y) {
    const note = el.dataset.note;
    el.classList.add("down");
    setTimeout(() => el.classList.remove("down"), 180);
    if (demo) { play(note); bubble(el, x, y); return; }   // while the song is being played to the child: just sound
    const target = quiz ? quiz.notes[quiz.pos] : song ? curNotes[songPos] : null;
    if (target && note !== target) {
      playOops();
      wobble(el);
      if (quiz) quizAnswer(note);
      return;
    }
    play(note);
    if (target) rightNote(note);                      // songs and quiz: show the answer on the card
    else bubble(el, x, y);                           // free play: the little bubble
    if (quiz) quizAnswer(note);
    else if (song) advanceSong(note);
    else showNow(note);                               // free play: show the note just played
  }

  function bubble(el, x, y) {
    const d = document.createElement("div");
    d.className = "bubble";
    d.style.setProperty("--c", el.style.getPropertyValue("--c"));
    d.style.setProperty("--cl", el.style.getPropertyValue("--cl"));
    d.style.left = x + "px";
    d.style.top = y + "px";
    document.body.appendChild(d);
    setTimeout(() => d.remove(), 950);
  }

  /* ---------------- Sound ---------------- */
  // The AudioContext is created at page load so all sounds are decoded before the first tap.
  // Browsers keep it "suspended" until a tap → unlockAudio() resumes it inside that tap.
  // iPhone / iPad fixes:
  //  * the ring/silent switch mutes Web Audio unless the page says it is a music player ("playback")
  //  * older iOS: a silent <audio> element started inside the tap moves the page into the playback session
  //  * after the screen was locked or another app played sound, iOS leaves the audio "interrupted" → resume
  try { if (navigator.audioSession) navigator.audioSession.type = "playback"; } catch (_) {}
  const IS_IOS = /iP(hone|ad|od)/.test(navigator.userAgent) ||
                 (navigator.platform === "MacIntel" && navigator.maxTouchPoints > 1);
  let silentEl = null;
  function unlockAudio() {
    try { if (navigator.audioSession && navigator.audioSession.type !== "playback") navigator.audioSession.type = "playback"; } catch (_) {}
    if (IS_IOS && !silentEl) {
      silentEl = new Audio("media/silence.wav");
      silentEl.loop = true;
      silentEl.setAttribute("playsinline", "");
      silentEl.play().catch(() => { silentEl = null; });   // try again on the next tap
    }
    if (ctx && ctx.state !== "running") ctx.resume().catch(() => {});
  }
  document.addEventListener("visibilitychange", () => {
    if (document.visibilityState === "visible" && ctx && ctx.state !== "running") ctx.resume().catch(() => {});
  });

  async function initAudio() {
    if (ctx) return;
    ctx = new (window.AudioContext || window.webkitAudioContext)();
    const comp = ctx.createDynamicsCompressor();   // prevents clipping when many keys are pressed
    master = ctx.createGain();
    master.gain.value = MAX_VOLUME;
    master.connect(comp).connect(ctx.destination);

    await Promise.all([...ALL_NOTES, "oops"].map(async (note) => {
      try {
        const res = await fetch(`sounds/${note}.wav`);
        const data = await res.arrayBuffer();
        buffers[note] = await new Promise((ok, fail) =>
          ctx.decodeAudioData(data, ok, fail));      // callback form for older Safari
      } catch (err) {
        console.warn("sound load failed", note, err);
      }
    }));
  }

  function play(note) {
    if (!ctx) return;
    if (ctx.state === "suspended") ctx.resume();
    const buf = buffers[note];
    if (buf) {
      const src = ctx.createBufferSource();
      src.buffer = buf;
      src.connect(master);
      src.start();
    } else {
      fallbackTone(note);                            // fallback if the sound file did not load
    }
  }

  // Soft, low kitten "mew" for a wrong note (songs and quiz only). It always glides and never holds a
  // piano pitch (see generate_assets.py). Many wrong taps in a row play it at most once every 0.7 s,
  // and never two at once, so it stays calm instead of noisy.
  // The microphone ignores the next moment, so the speaker's own sound is never mistaken for the piano.
  let micQuietUntil = 0, oopsSrc = null, oopsAt = 0;
  function playOops() {
    micQuietUntil = performance.now() + 600;
    if (!ctx || !buffers.oops) return;
    if (ctx.state === "suspended") ctx.resume();
    const now = performance.now();
    if (now - oopsAt < 700) return;                  // fast repeated wrong taps: calm, never stacked
    oopsAt = now;
    try { oopsSrc && oopsSrc.stop(); } catch (_) {}  // only one mew at a time
    oopsSrc = ctx.createBufferSource();
    oopsSrc.buffer = buffers.oops;
    oopsSrc.connect(master);
    oopsSrc.start();
  }
  function wobble(el) {                              // wrong key gives a little wiggle (no red, no scolding)
    el.classList.remove("oops"); void el.offsetWidth; el.classList.add("oops");
    setTimeout(() => el.classList.remove("oops"), 420);
  }

  function fallbackTone(note) {
    const freq = 440 * 2 ** ((noteNum(note) - 69) / 12);
    const o = ctx.createOscillator(), g = ctx.createGain(), t = ctx.currentTime;
    o.type = "triangle";
    o.frequency.value = freq;
    g.gain.setValueAtTime(0.0001, t);
    g.gain.exponentialRampToValueAtTime(0.8, t + 0.01);
    g.gain.exponentialRampToValueAtTime(0.0001, t + 1.2);
    o.connect(g).connect(master);
    o.start(t);
    o.stop(t + 1.3);
  }

  /* ---------------- Play-along songs (data from the Python backend) ---------------- */
  async function loadSongs() {
    let data = null;
    for (const url of ["api/songs", "songs.json"]) {   // use the API when there is a backend; static file otherwise
      try {
        const r = await fetch(url);
        if (r.ok) { data = await r.json(); break; }
      } catch (_) { /* try the next one */ }
    }
    if (!data) return;
    songSel.innerHTML = "";
    const free = new Option(T.free, "");                 // default: free play
    songSel.add(free);
    for (const sg of data.songs) {
      const o = new Option(T[sg.title] || sg.title, sg.id);
      o._song = sg;
      songSel.add(o);
    }
    songSel.value = "";
  }

  // Move the melody to the current clef's octave (songs are stored in treble C4–C5; bass drops one octave)
  function updateNotes() {
    curNotes = song ? song.notes.map((n) => (clef === "G" ? n : n.slice(0, -1) + (+n.slice(-1) - 1))) : [];
  }

  songSel.addEventListener("change", () => {
    stopDemo();
    holdUntil = 0; clearTimeout(holdT);
    unfoldMenus();
    song = songSel.selectedOptions[0]._song || null;
    songPos = 0;
    updateNotes();
    highlightNext();
    setPlayBtn();
    if (listening) pianoStatus.textContent = T[pianoState] || "";
    if (song) startDemo();                           // a song was picked → first show the child how it goes
  });

  function advanceSong(note) {
    if (note !== curNotes[songPos]) return;          // only the right note moves the song forward
    songPos++;
    if (songPos < curNotes.length) foldMenus();     // the child is playing → menus fold away
    else unfoldMenus();
    if (songPos >= curNotes.length) {              // end of song
      keysEl.classList.add("celebrate");
      setTimeout(() => keysEl.classList.remove("celebrate"), 1200);
      songPos = 0;
    }
    highlightNext();
  }

  /* ---------------- Playing along with the child's real piano ---------------- */
  // When the right note is heard, move to the next note until the song ends
  let listening = false, pianoState = "";

  function flashKey(id) {
    const el = keyEls[id];
    el.classList.add("down", "heard");
    setTimeout(() => el.classList.remove("down", "heard"), 260);
    const r = el.getBoundingClientRect();
    bubble(el, r.left + r.width / 2, r.top + r.height * 0.4);
  }

  function onPianoNote(num) {
    stillPlaying();
    if (demo || performance.now() < micQuietUntil) return;   // ignore our own speaker (demo / "mew")
    const target = quiz ? quiz.notes[quiz.pos] : song ? curNotes[songPos] : null;
    // The mic is sometimes off by an octave → compare pitch class only (Do/Re/Mi…) and map to the current clef's octave
    const pc = PC[num % 12];
    const id = target && target.slice(0, -1) === pc ? target : pc + baseOct();
    if (!keyEls[id]) return;                         // ignore notes outside the current set of keys
    if (target && id !== target) {                   // wrong note on the real piano → soft "mew", no progress
      playOops();
      wobble(keyEls[id]);
      if (quiz) quizAnswer(id);
      return;
    }
    flashKey(id);
    if (target) rightNote(id);                       // right note on the real piano: same reward
    if (quiz) quizAnswer(id);
    else if (song) advanceSong(id);
    else showNow(id);
  }

  // Microphone: choosing "real piano" leaves fullscreen and asks the browser directly (its own
  // Allow / Block prompt). Our dialog only appears if the microphone was blocked earlier.
  const micDialog = document.getElementById("micDialog");
  const micTitle = document.getElementById("micTitle");
  const micBody = document.getElementById("micBody");
  const micOk = document.getElementById("micOk");
  const micClose = document.getElementById("micClose");
  let micPending = false;                          // while the browser prompt is open, do not re-enter fullscreen

  function setMicDialog() {
    if (!T.micBlocked) return;
    micBody.textContent = T.micBlocked;
    micOk.textContent = T.retry;
  }
  function openMicDialog() { setMicDialog(); micDialog.hidden = false; }
  function closeMicDialog() { micDialog.hidden = true; }

  function beginListening(state) {
    listening = true;
    pianoState = state;
    pianoStatus.textContent = T[state];
    if (song && !quiz) { songPos = 0; highlightNext(); }     // start from the first note
  }

  // Browsers hide or auto-dismiss permission prompts in fullscreen, so leave fullscreen first
  async function leaveFullscreen() {
    const exit = document.exitFullscreen || document.webkitExitFullscreen;
    if (!fsElement() || !exit) return;
    try { await exit.call(document); } catch (_) {}
    await new Promise((r) => setTimeout(r, 200));  // let the browser finish the transition
  }

  async function tryMic() {
    micPending = true;
    closeMicDialog();
    await leaveFullscreen();
    try {
      await PianoInput.startMic(onPianoNote);       // the browser shows its own Allow / Block prompt
      beginListening("listening");
    } catch (_) {
      openMicDialog();                             // blocked before → show how to turn it back on
    }
    micPending = false;
  }

  function startPiano() { return tryMic(); }

  micOk.addEventListener("click", tryMic);
  // Closing the dialog without a working microphone → back to the on-screen keys
  micClose.addEventListener("click", () => { closeMicDialog(); if (!listening) setMode("screen"); });

  function stopPiano(keepMessage) {
    listening = false;
    PianoInput.stop();
    if (!keepMessage) { pianoState = ""; pianoStatus.textContent = ""; }
  }

  // Play-mode menu: the microphone is only requested when "real piano" is chosen
  function setMode(m) {
    modeSel.value = m;
    modeSel.classList.toggle("active", m === "piano");
  }
  modeSel.addEventListener("change", () => {
    setMode(modeSel.value);
    if (modeSel.value === "piano") { if (!listening) startPiano(); }
    else if (listening) stopPiano();
    else closeMicDialog();
  });

  /* ---------------- Quiz ---------------- */
  // Every quiz tests all 8 white-key notes of the current clef exactly once, in a new random order;
  // wrong → the correct key flashes; right → next note; all 8 done → celebration; 5 wrong in a row → end gently
  const QUIZ_LEN = WHITE_SLOTS.length, MAX_WRONG = 5;
  const quizBtn = document.getElementById("quizBtn");
  let quiz = null;

  function pickQuizNotes() {
    const pool = WHITE_SLOTS.map(noteOf);           // all 8 notes
    for (let i = pool.length - 1; i > 0; i--) {     // Fisher–Yates shuffle
      const j = Math.floor(Math.random() * (i + 1));
      [pool[i], pool[j]] = [pool[j], pool[i]];
    }
    return pool.slice(0, QUIZ_LEN);
  }

  function quizProgress() {
    statusEl.textContent = "";                       // no counters or words: they mean nothing to a toddler
  }

  function showQuizTarget() {
    Object.values(keyEls).forEach((k) => k.classList.remove("next"));
    showTarget(quiz.notes[quiz.pos], true);
    quizProgress();
  }

  function revealKey(note) {                        // wrong answer: flash the correct key and briefly show it on the card
    const el = keyEls[note];
    el.classList.remove("reveal"); void el.offsetWidth; el.classList.add("reveal");
    showNow(note);
    clearTimeout(revealKey.t);
    revealKey.t = setTimeout(() => { el.classList.remove("reveal"); if (quiz) showNow(quiz.notes[quiz.pos], true); }, 1800);
  }

  function quizAnswer(note) {
    const target = quiz.notes[quiz.pos];
    if (note === target) {
      quiz.pos++;
      quiz.wrong = 0;
      clearTimeout(revealKey.t);
      keyEls[target].classList.remove("reveal");
      if (quiz.pos >= QUIZ_LEN) return finishQuiz(true);
      foldMenus();                                   // the child keeps playing → menus stay out of the way
      showQuizTarget();
    } else {
      quiz.wrong++;
      revealKey(target);
      if (quiz.wrong >= MAX_WRONG) finishQuiz(false);
    }
  }



  function finishQuiz(success) {
    quizProgress();
    if (success) {
      keysEl.classList.add("celebrate");
      setTimeout(() => keysEl.classList.remove("celebrate"), 1200);
      setTimeout(bubbleParty, 500);                  // after the last answer's reward
    }
    endQuiz();                                       // no "All correct" text: the bubbles are the reward
  }

  function startQuiz() {
    stopDemo();
    endBubbleParty();
    holdUntil = 0; clearTimeout(holdT);              // a new quiz starts at once (no answer still on hold)
    if (song) { songSel.value = ""; song = null; updateNotes(); }
    quiz = { notes: pickQuizNotes(), pos: 0, wrong: 0 };
    keysEl.classList.add("quiz");                    // hide the staff on the keys so kids must read the card
    songSel.disabled = clefSel.disabled = true;
    quizBtn.classList.add("active");
    quizBtn.textContent = `■ ${T.quizEnd}`;
    setPlayBtn();
    showQuizTarget();
    foldMenus(true);
  }

  function endQuiz() {
    quiz = null;
    clearTimeout(revealKey.t);
    Object.values(keyEls).forEach((k) => k.classList.remove("reveal"));
    keysEl.classList.remove("quiz");
    songSel.disabled = clefSel.disabled = false;
    quizBtn.classList.remove("active");
    quizBtn.textContent = T.quiz;
    setPlayBtn();
    unfoldMenus();
    statusEl.textContent = "";
    const clearCard = () => {
      nowEl.classList.add("empty");
      nowStaff.src = `staff/${clef}/clef.svg`;
      nowNote = null;
    };
    clearTimeout(holdT);
    const wait = holdUntil - performance.now();     // the last right answer stays visible for a moment
    if (wait > 0) holdT = setTimeout(clearCard, wait); else clearCard();
  }

  quizBtn.addEventListener("click", () => (quiz ? endQuiz() : startQuiz()));

  /* ---------------- Listen: the app plays the song slowly, showing every note ---------------- */
  // Each note: the key bounces + lights up, the card shows its staff note and shape, and it sounds.
  const BEAT_MS = 850;                               // slow (about 70 beats per minute) so toddlers can follow
  const playBtn = document.getElementById("playBtn");
  let demo = null;                                   // { i, timer } while playing

  function setPlayBtn() {
    playBtn.disabled = !!quiz;                       // songs: the melody · "Pick A Song" (free play): the scale
    playBtn.classList.toggle("active", !!demo);
    playBtn.textContent = demo ? `■ ${T.stop}` : `\u25B6\uFE0E ${T.play}`;
  }
  function demoStep() {
    stillPlaying();
    if (!demo) return;
    if (demo.i >= demo.notes.length) return stopDemo();
    const note = demo.notes[demo.i];
    Object.values(keyEls).forEach((k) => k.classList.remove("next"));
    const el = keyEls[note];
    el.classList.add("next", "down");
    setTimeout(() => el.classList.remove("down"), 220);
    showNow(note);
    play(note);
    const beats = demo.beats[demo.i] || 1;
    demo.i++;
    demo.timer = setTimeout(demoStep, beats * BEAT_MS);
  }
  function startDemo() {
    if (quiz) return;
    unlockAudio();
    clearTimeout(holdT);
    // A song plays its melody; free play ("Pick A Song") plays the scale Do → high Do of the current clef
    const notes = song ? curNotes : WHITE_SLOTS.map(noteOf);
    const beats = song && song.beats ? song.beats : notes.map(() => 1);
    demo = { i: 0, timer: 0, notes, beats };
    setPlayBtn();
    demoStep();
  }
  function stopDemo() {
    if (!demo) return;
    clearTimeout(demo.timer);
    demo = null;
    setPlayBtn();
    songPos = 0;                                     // now it's the child's turn, from the first note
    highlightNext();                                 // (free play: clears the highlight and the counter)
  }
  // While a song (or the scale) is playing by itself, ANY tap on the page stops it at once.
  // Capture phase, so it runs before everything else; the tap itself still does its normal job
  // (a key still sounds), except on the Play/Stop button, which must not start the song again.
  let demoTapStop = false;                           // true from the stopping tap until its click is over
  document.addEventListener("pointerdown", () => {
    demoTapStop = !!demo;
    if (demo) stopDemo();
  }, true);
  document.addEventListener("click", () => { demoTapStop = false; });
  playBtn.addEventListener("click", () => {
    if (demoTapStop) return;                         // this same tap already stopped the song
    demo ? stopDemo() : startDemo();
  });

  /* ---------------- Menus fold away while the child plays ---------------- */
  // As soon as a song is being played (first right note) or a quiz starts, the menus fold into one small
  // button so the child looks at the keys, not the dropdowns. A single tap does nothing — it takes a
  // double-tap (a grown-up gesture) to open them. They come back by themselves when the song or quiz ends.
  const menuBtn = document.getElementById("menuBtn");
  const barEl = document.querySelector(".top .bar");
  let menuKeepOpenUntil = 0, menuLastTap = 0;
  function foldMenus(force) {
    if (!force && performance.now() < menuKeepOpenUntil) return;   // a grown-up is using the menus right now
    document.getElementById("app").classList.add("menu-folded");
  }
  function unfoldMenus() {
    document.getElementById("app").classList.remove("menu-folded");
  }
  function openMenusByGrownUp() {
    unfoldMenus();
    menuKeepOpenUntil = performance.now() + 8000;   // stays open while being used; folds again later
  }
  menuBtn.addEventListener("pointerup", (e) => {
    e.preventDefault();
    const now = performance.now();
    if (now - menuLastTap < 450) { menuLastTap = 0; openMenusByGrownUp(); }
    else menuLastTap = now;
  });
  menuBtn.addEventListener("keydown", (e) => {    // keyboard users (accessibility): Enter / Space opens directly
    if (e.key === "Enter" || e.key === " ") { e.preventDefault(); openMenusByGrownUp(); }
  });
  for (const type of ["pointerdown", "change", "keydown"]) {
    barEl.addEventListener(type, (e) => {
      // only after a grown-up double-tapped them open: keep them open while they are being used
      if (e.target !== menuBtn && performance.now() < menuKeepOpenUntil) menuKeepOpenUntil = performance.now() + 8000;
    });
  }

  function highlightNext() {
    Object.values(keyEls).forEach((k) => k.classList.remove("next"));
    setTimeout(applyCue, 0);                         // the key cue follows at once (the card may wait for its hold)
    if (song) {
      keyEls[curNotes[songPos]].classList.add("next");
      showTarget(curNotes[songPos]);                  // play-along: show the next note to play
    }
    statusEl.textContent = "";                       // no "1 / 42" counter (means nothing to a toddler)
  }

  /* ---------------- Fullscreen + landscape lock (so toddlers can't accidentally exit) ---------------- */
  // There is no start screen: the first tap anywhere unlocks sound, goes fullscreen and locks landscape.
  // If the child swipes out of fullscreen, the next tap anywhere goes back in (the tap still works as usual).
  const isInstalled = () =>
    matchMedia("(display-mode: fullscreen), (display-mode: standalone)").matches ||
    navigator.standalone === true;                       // iOS "Add to Home Screen"
  const fsElement = () => document.fullscreenElement || document.webkitFullscreenElement;

  // Computers: no automatic fullscreen — browsers always show a "Press Esc to exit full screen" banner that
  // covers the screen, and a mouse cannot swipe out by accident anyway. Phones and tablets go fullscreen.
  const TOUCH_DEVICE = matchMedia("(pointer: coarse)").matches;
  let exited = false;                                // a grown-up tapped "Exit": no more fullscreen or back trap
  function enterFullscreen(force = false) {
    const el = document.documentElement;
    const req = el.requestFullscreen || el.webkitRequestFullscreen;
    if (!req || fsElement() || isInstalled()) return;
    if (!force && (exited || !TOUCH_DEVICE)) return;
    // Must be called synchronously inside the tap, or the browser refuses
    Promise.resolve(req.call(el, { navigationUI: "hide" })).then(lockLandscape).catch(() => {});
  }

  async function lockLandscape() {
    try { await screen.orientation.lock("landscape"); } catch (_) { /* not supported on iOS → CSS rotation instead */ }
  }

  // Trap the "back" gesture/button so a toddler pressing back does not leave the app
  function trapBack() {
    history.pushState({ toddler: true }, "");
    window.addEventListener("popstate", () => { if (!exited) history.pushState({ toddler: true }, ""); });
  }

  // "Exit" (for grown-ups, in the menus): leave fullscreen and stop holding the child in the app.
  // After that the same button says "Full screen" and brings the child-safe mode back.
  const exitBtn = document.getElementById("exitBtn");
  function setExitBtn() {
    exitBtn.textContent = exited ? T.fullscreen : T.exit;
    exitBtn.setAttribute("aria-pressed", String(exited));
  }
  exitBtn.addEventListener("click", () => {
    if (!exited) {
      exited = true;
      const exit = document.exitFullscreen || document.webkitExitFullscreen;
      if (fsElement() && exit) Promise.resolve(exit.call(document)).catch(() => {});
      try { screen.orientation.unlock(); } catch (_) {}
    } else {
      exited = false;
      enterFullscreen(true);                         // inside the tap, so the browser allows it
    }
    setExitBtn();
  });

  let started = false;
  /* ---------------- Keep the screen awake (like a video player) ---------------- */
  // While the app is open and visible, the screen never dims or locks (phones, tablets and computers).
  //  1. Screen Wake Lock API (Chrome, Edge, Android, Safari 16.4+, Firefox 126+), requested at once and again
  //     after every return to the app (browsers drop it when the app is hidden)
  //  2. Fallback for browsers without it (or when it is refused): a tiny silent looping video, which
  //     phones treat like a playing video and keep the screen on
  let wakeLock = null, keepVideo = null;
  async function holdScreen() {
    if (document.visibilityState !== "visible") return;
    if ("wakeLock" in navigator) {
      if (wakeLock) return;
      try {
        wakeLock = await navigator.wakeLock.request("screen");
        wakeLock.addEventListener("release", () => { wakeLock = null; });
        return;
      } catch (_) { wakeLock = null; }               // refused (e.g. no tap yet on Safari) → fallback too
    }
    playKeepAwakeVideo();
  }
  function playKeepAwakeVideo() {
    if (!keepVideo) {
      keepVideo = document.createElement("video");
      keepVideo.setAttribute("playsinline", "");
      keepVideo.setAttribute("muted", "");
      keepVideo.muted = true;
      keepVideo.loop = true;
      keepVideo.setAttribute("aria-hidden", "true");
      keepVideo.style.cssText = "position:fixed;width:1px;height:1px;opacity:0;pointer-events:none;left:0;top:0";
      for (const [src, type] of [["media/keep-awake.webm", "video/webm"], ["media/keep-awake.mp4", "video/mp4"]]) {
        const so = document.createElement("source"); so.src = src; so.type = type; keepVideo.appendChild(so);
      }
      document.body.appendChild(keepVideo);
    }
    if (keepVideo.paused) keepVideo.play().catch(() => {});
  }
  function stillPlaying() { holdScreen(); }
  holdScreen();                                      // Chrome / Edge / Android allow it without a tap
  document.addEventListener("visibilitychange", () => { if (document.visibilityState === "visible") holdScreen(); });
  setInterval(holdScreen, 20 * 1000);                // safety net: take it back if the system dropped it

  function onAnyTap(e) {
    stillPlaying();
    unlockAudio();                                       // must run inside a user gesture (iOS / Chrome)
    if (!started) { started = true; trapBack(); lockLandscape(); }
    // Opening a dropdown should not be interrupted; fullscreen then starts on the next tap elsewhere
    // (and not while the microphone prompt is open or the microphone dialog is showing)
    const t = e.target.closest ? e.target : document.body;
    if (!micPending && micDialog.hidden && !t.closest("select, .cs")) enterFullscreen();
  }
  // Capture phase: runs before the key's own handler, so the very first tap on a key also plays it.
  // Browsers allow fullscreen on different events (mouse: pointerdown; touch: pointerup), so listen to both.
  for (const type of ["pointerdown", "pointerup", "touchend", "click", "keydown"]) document.addEventListener(type, onAnyTap, true);

  const onFsChange = () => setTimeout(layoutBlackKeys, 100);
  document.addEventListener("fullscreenchange", onFsChange);
  document.addEventListener("webkitfullscreenchange", onFsChange);

  /* ---------------- PWA ---------------- */
  if ("serviceWorker" in navigator) {
    window.addEventListener("load", () => {
      navigator.serviceWorker.register("sw.js").catch((e) => console.warn("SW", e));
    });
  }

  /* ---------------- Clef menu: treble / bass ---------------- */
  const clefSel = document.getElementById("clef");
  const clefIcon = document.getElementById("clefIcon");
  const appEl = document.getElementById("app");
  appEl.dataset.clef = clef;                       // whole layout: pink theme (treble) / light blue (bass)
  clefSel.value = clef;
  clefIcon.src = `staff/${clef}/clef.svg`;
  clefSel.addEventListener("change", () => {
    stopDemo();
    holdUntil = 0; clearTimeout(holdT);
    clef = clefSel.value;
    appEl.dataset.clef = clef;
    try { localStorage.setItem("clef", clef); } catch (_) {}
    clefIcon.src = `staff/${clef}/clef.svg`;
    buildKeys();                                     // rebuild the keys for this clef's octave
    updateNotes();
    songPos = 0;
    nowNote = null;
    nowEl.classList.add("empty");
    nowStaff.src = `staff/${clef}/clef.svg`;
    highlightNext();
    if (T.notes) applyLang();
  });

  nowEl.addEventListener("pointerdown", () => {
    if (!nowNote || nowEl.classList.contains("empty")) return;
    play(nowNote);
    nowEl.classList.remove("pop"); void nowEl.offsetWidth; nowEl.classList.add("pop");
  });

  /* ---------------- Custom dropdowns ---------------- */
  // The native pop-up lists of <select> open in the phone's own orientation (upright) even though the app
  // is turned sideways, and they cannot show pictures. So every menu gets a drawn list instead: it opens
  // inside the app (always landscape), scrolls with a visible scroll bar, and shows little icons.
  // The real <select> stays (hidden) and keeps the value, so all the other code is unchanged.
  // Accessible: button + listbox roles, arrow keys, Enter / Space, Escape.
  const ICON = {
    note:   '<svg viewBox="0 0 24 24"><path d="M9 17V5.5l10-2.2V15" fill="none"/><circle cx="6.4" cy="17.2" r="2.8"/><circle cx="16.4" cy="15.2" r="2.8"/></svg>',
    star:   '<svg viewBox="0 0 24 24"><path d="M12 2.8l2.8 5.9 6.4.8-4.7 4.4 1.2 6.4L12 17.1l-5.7 3.2 1.2-6.4-4.7-4.4 6.4-.8z"/></svg>',
    lamb:   '<svg viewBox="0 0 24 24"><path d="M7 16.5a3.2 3.2 0 0 1-.4-6.3 3.6 3.6 0 0 1 6.8-1.8 3.3 3.3 0 0 1 4.6 2.8 2.8 2.8 0 0 1-.8 5.3z"/><circle cx="18.6" cy="12.6" r="2.3" class="i-dark"/><path d="M9 16.5v3M14.5 16.5v3" fill="none"/></svg>',
    joy:    '<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="8.6"/><path d="M8.3 13.6a4.3 4.3 0 0 0 7.4 0" fill="none"/><circle cx="9" cy="10" r="1" class="i-ink"/><circle cx="15" cy="10" r="1" class="i-ink"/></svg>',
    bell:   '<svg viewBox="0 0 24 24"><path d="M12 3.6a1.5 1.5 0 0 1 1.5 1.5v.6A6 6 0 0 1 18 11.5v4l2 2.4H4l2-2.4v-4a6 6 0 0 1 4.5-5.8v-.6A1.5 1.5 0 0 1 12 3.6z"/><circle cx="12" cy="20.2" r="1.7"/></svg>',
    keys:   '<svg viewBox="0 0 24 24"><rect x="2.5" y="5" width="19" height="14" rx="2"/><path d="M8.2 5v14M13.8 5v14M19.4 5v14" fill="none"/><rect x="6.6" y="5" width="3.2" height="7.5" class="i-ink"/><rect x="12.2" y="5" width="3.2" height="7.5" class="i-ink"/></svg>',
    mic:    '<svg viewBox="0 0 24 24"><rect x="8.5" y="3" width="7" height="11.5" rx="3.5"/><path d="M5.5 11.5a6.5 6.5 0 0 0 13 0M12 18v3M8.5 21h7" fill="none"/></svg>',
    globe:  '<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="8.6"/><path d="M3.4 12h17.2M12 3.4c2.6 2.4 2.6 14.8 0 17.2M12 3.4c-2.6 2.4-2.6 14.8 0 17.2" fill="none"/></svg>',
  };
  const SONG_ICON = { "": "note", twinkle: "star", mary: "lamb", ode: "joy", jingle: "bell" };
  const iconOf = {
    song: (v) => ICON[SONG_ICON[v] || "note"],
    mode: (v) => ICON[v === "piano" ? "mic" : "keys"],
    clef: (v) => `<img src="staff/${v || clef}/clef.svg" alt="">`,
    lang: () => ICON.globe,
  };
  const esc = (t) => t.replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
  const customSelects = [];

  function enhanceSelect(sel) {
    const kind = sel.id, iconFn = iconOf[kind] || (() => "");
    const iconOnly = kind === "clef";                // the clef menu shows only the treble / bass clef pictures
    const wrap = document.createElement("span");
    wrap.className = "cs cs-" + kind + (iconOnly ? " cs-icononly" : "");
    const pick = sel.parentNode.classList.contains("clef-pick") ? sel.parentNode : null;
    if (pick) {                                      // the clef menu: its picture now lives inside the button
      pick.parentNode.insertBefore(wrap, pick);
      wrap.append(...pick.children);
      pick.remove();
    } else {
      sel.parentNode.insertBefore(wrap, sel);
      wrap.appendChild(sel);
    }
    sel.classList.add("cs-native");
    sel.tabIndex = -1;
    sel.setAttribute("aria-hidden", "true");
    const btn = document.createElement("button");
    btn.type = "button";
    btn.className = "select cs-btn " + [...sel.classList].filter((c) => c !== "select" && c !== "cs-native").join(" ");
    btn.setAttribute("aria-haspopup", "listbox");
    btn.setAttribute("aria-expanded", "false");
    const list = document.createElement("div");
    list.className = "cs-list";
    list.id = kind + "List";
    list.setAttribute("role", "listbox");
    list.hidden = true;
    btn.setAttribute("aria-controls", list.id);
    wrap.append(btn, list);

    let shown = "";
    function render() {
      const o = sel.options[sel.selectedIndex];
      const key = [sel.selectedIndex, o ? o.textContent : "", sel.disabled, sel.getAttribute("aria-label"), sel.className].join("|");
      if (key === shown) return;
      shown = key;
      btn.innerHTML = `<span class="cs-ico" aria-hidden="true">${iconFn(o ? o.value : "")}</span>` +
        (iconOnly ? "" : `<span class="cs-label">${esc(o ? o.textContent : "")}</span>`);
      btn.disabled = sel.disabled;
      btn.classList.toggle("active", sel.classList.contains("active"));
      btn.setAttribute("aria-label", `${sel.getAttribute("aria-label") || ""}: ${o ? o.textContent : ""}`);
    }
    function close(focusBtn) {
      if (list.hidden) return;
      list.hidden = true;
      btn.setAttribute("aria-expanded", "false");
      wrap.classList.remove("open");
      if (focusBtn) btn.focus();
    }
    function choose(value) {
      if (sel.value !== value) {
        sel.value = value;
        sel.dispatchEvent(new Event("change", { bubbles: true }));
      }
      render();
      close(true);
    }
    function open() {
      customSelects.forEach((c) => c !== api && c.close());
      list.innerHTML = "";
      [...sel.options].forEach((o) => {
        if (o.hidden || o.disabled) return;
        const it = document.createElement("div");
        it.className = "cs-opt";
        it.setAttribute("role", "option");
        it.tabIndex = -1;
        it.dataset.value = o.value;
        const on = o.value === sel.value;
        it.setAttribute("aria-selected", String(on));
        it.innerHTML = `<span class="cs-ico" aria-hidden="true">${iconFn(o.value)}</span>` + (iconOnly ? "" : `<span>${esc(o.textContent)}</span>`);
        if (iconOnly) it.setAttribute("aria-label", o.textContent);   // no words shown; screen readers still hear the name
        it.addEventListener("click", (e) => { e.stopPropagation(); choose(o.value); });
        list.appendChild(it);
      });
      list.hidden = false;
      wrap.classList.add("open");
      btn.setAttribute("aria-expanded", "true");
      const cur = list.querySelector('[aria-selected="true"]') || list.firstElementChild;
      if (cur) { cur.scrollIntoView({ block: "nearest" }); cur.focus({ preventScroll: true }); }
    }
    btn.addEventListener("click", (e) => { e.stopPropagation(); list.hidden ? open() : close(true); });
    btn.addEventListener("keydown", (e) => {
      if (e.key === "ArrowDown" || e.key === "ArrowUp") { e.preventDefault(); open(); }
    });
    list.addEventListener("keydown", (e) => {
      const items = [...list.children], i = items.indexOf(document.activeElement);
      if (e.key === "ArrowDown") { e.preventDefault(); (items[i + 1] || items[0]).focus(); }
      else if (e.key === "ArrowUp") { e.preventDefault(); (items[i - 1] || items[items.length - 1]).focus(); }
      else if (e.key === "Home") { e.preventDefault(); items[0].focus(); }
      else if (e.key === "End") { e.preventDefault(); items[items.length - 1].focus(); }
      else if (e.key === "Enter" || e.key === " ") { e.preventDefault(); if (i >= 0) choose(items[i].dataset.value); }
      else if (e.key === "Escape" || e.key === "Tab") { close(e.key === "Escape"); }
      e.stopPropagation();                           // the computer-keyboard piano ignores keys used in a menu
    });
    new MutationObserver(render).observe(sel, { attributes: true, childList: true, subtree: true, characterData: true });
    const api = { sel, btn, render, close };
    customSelects.push(api);
    render();
    return api;
  }
  // tap outside a list closes it
  document.addEventListener("pointerdown", (e) => {
    if (!e.target.closest || !e.target.closest(".cs")) customSelects.forEach((c) => c.close());
  });
  // values also change from code (e.g. the quiz resets the song menu), so refresh the labels regularly
  setInterval(() => customSelects.forEach((c) => c.render()), 300);

  // "Pick A Song" gently wiggles and glows until a song is chosen (not during a quiz or the Listen demo)
  function updateSongHint() {
    const c = customSelects.find((x) => x.sel === songSel);
    if (c) c.btn.classList.toggle("attn", !songSel.value && !quiz && !demo && !songSel.disabled);
  }
  setInterval(updateSongHint, 300);

  for (const s of [clefSel, modeSel, langSel, songSel]) enhanceSelect(s);

  nowStaff.src = `staff/${clef}/clef.svg`;
  initAudio();                                   // decode all sounds now; they start playing after the first tap
  loadI18n().then(loadSongs);
})();
